<?php
declare(strict_types=1);

// Branchio SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BranchioUtility::setRegistrar(function (BranchioUtility $u): void {
    $u->clean = [BranchioClean::class, 'call'];
    $u->done = [BranchioDone::class, 'call'];
    $u->make_error = [BranchioMakeError::class, 'call'];
    $u->feature_add = [BranchioFeatureAdd::class, 'call'];
    $u->feature_hook = [BranchioFeatureHook::class, 'call'];
    $u->feature_init = [BranchioFeatureInit::class, 'call'];
    $u->fetcher = [BranchioFetcher::class, 'call'];
    $u->make_fetch_def = [BranchioMakeFetchDef::class, 'call'];
    $u->make_context = [BranchioMakeContext::class, 'call'];
    $u->make_options = [BranchioMakeOptions::class, 'call'];
    $u->make_request = [BranchioMakeRequest::class, 'call'];
    $u->make_response = [BranchioMakeResponse::class, 'call'];
    $u->make_result = [BranchioMakeResult::class, 'call'];
    $u->make_point = [BranchioMakePoint::class, 'call'];
    $u->make_spec = [BranchioMakeSpec::class, 'call'];
    $u->make_url = [BranchioMakeUrl::class, 'call'];
    $u->param = [BranchioParam::class, 'call'];
    $u->prepare_auth = [BranchioPrepareAuth::class, 'call'];
    $u->prepare_body = [BranchioPrepareBody::class, 'call'];
    $u->prepare_headers = [BranchioPrepareHeaders::class, 'call'];
    $u->prepare_method = [BranchioPrepareMethod::class, 'call'];
    $u->prepare_params = [BranchioPrepareParams::class, 'call'];
    $u->prepare_path = [BranchioPreparePath::class, 'call'];
    $u->prepare_query = [BranchioPrepareQuery::class, 'call'];
    $u->graphql_body = [BranchioGraphql::class, 'body'];
    $u->graphql_errors = [BranchioGraphql::class, 'errors'];
    $u->result_basic = [BranchioResultBasic::class, 'call'];
    $u->result_body = [BranchioResultBody::class, 'call'];
    $u->result_headers = [BranchioResultHeaders::class, 'call'];
    $u->transform_request = [BranchioTransformRequest::class, 'call'];
    $u->transform_response = [BranchioTransformResponse::class, 'call'];
});
